{
    'name': 'Theme Intello',
    'summary': 'Theme Intello Idea',
    'version': '1.0',
    'license': 'AGPL-3',
    'description': """
        Tema pricipal para la empresa Intello Idea SAS
    """,
    'category': 'Theme/Creative',
    'author': "Intello Idea",
    'website': "http://www.intelloidea.com",
    'depends': ['website', 'website_theme_install'],
    'data': [
        'security/ir.model.access.csv',
        'data/website.menu.csv',
        'views/website_views.xml',
        'views/assets_intello.xml',
        'views/website_layout.xml',
        'views/web_home_page.xml',
        'views/web_odoo_home_page.xml',
        'views/web_odoo_our_page.xml',
        'views/web_develop_page.xml',
        'views/web_sap_consulting_page.xml',
        'views/web_app_movil_page.xml',
        'views/web_our_work_page.xml',
        'views/web_odoo_know_more_page.xml',
        'views/web_odoo_demo_page.xml',
        'views/web_login_inherit_page.xml',
        'views/web_thank_us_inherit_page.xml',
        'views/web_error_404_page.xml',
        'views/web_contac_us_inherit_page.xml',

    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}
